# Metadata
title: "T's Twitch Toolkit"
favicon: https://lh3.googleusercontent.com/-jVm4_gboAh4/WyPzVps7m4I/AAAAAAAABTI/0GtYnDR7Sg8KSZMhEpwM3FvFCCs41H-IACEwYBhgLKtMDAL1Ocqxw0DPFWvea2QXaWYbj9ZoUy9AE3LFSGjEDoKrsdVWHXi7jjxKkRvvvIEySVl5I4GoOUeDXDaDq9TESCXN-gtlDtT0UT6mz6NppKTZPxSoNc37d8XdUPoNyrk9bA730eoVFOQq_41Z8zWLlvr6Xml-0oPMO2ntY4j5odeh3RaAQcKqG_nT0qAcF-4TcapNqOTHdVw0wCZg-el7snWHzzWXLtuJnpPw5eWM1TNCfxqHw1r-jQYPFfVUEC3QEDYVf9oYt4bloSDM-H7Tvr9sE9ttHKV8_gzke96eY-JI7Opxn_fGi-aF8pj4YfKgGDYTzqXOFsLEUdrWVL_hmeWDCXYGMhH6nd0wjiJFKsiZGZVdoarcXNVJZF4jD1XwE-zL651RkC2FIVpCCUju-wr7WTTYbGVTkIA35z7LuUT-m5OmrOioFEUuvG03WH8dEBex_nNppVs44p98fvJROqJv7-QdPEwryjaWaOrm2S2Ek5AUxpT3XbdXjJa0yWdSQ3d_102IJQA1Pu0dqdYhamFs_LFFJtUQ6fzLv14eAuuXlu9PwWeFw0OvOT3zD_cE_VIJh_TRqtFdgWMoOsomlarte-jnMibiInYAK6KPf8XtyD5Qw0NTggwY/w140-h140-p/Profile_T.png
description: >-
  An expanded item list specifically genterated for AlsoKnownAsT's Twitch Toolkit
  
baseurl: '/T-TTK' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username: 'AlsoKnownAsT'

# Item list settings
store:
  traits:
    # Whether or not the trait list will display conflicts with other traits.
    conflicts: true
    # Whether or not the trait list will display trait stats.
    stats: true
    # Whether or not the trait list will display karma type overrides.
    karma: true
    # Whether or not the trait list will display whether or not a trait bypasses the trait limit.
    limit: true
    # Whether or not the trait list will display trait descriptions.
    description: true
    # Whether or not the trait list will display the command a viewer should type for adding/removing that trait.
    usage: false
  kinds:
    # Whether or not the kind list will display karma type overrides.
    karma: true
    # Whether or not the kind list will display the command a viewer should type for purchasing that kind.
    usage: false
  items:
    # Whether or not the item list will display an item's in-game category.
    category: true
    # Whether or not the item list will display an item's purchase weight.
    weight: false
    # Whether or not the item list will display an item's karma type override.
    karma: true
    # Whether or not the item list will display an item's quantity limit.
    quantity: true
    # Whether or not the item list will display the mod that added it.
    mod: true
    # Whether or not the item list will display the command a viewer should type for purchasing that item.
    usage: true
  events:
    # Whether or not the event list will display the command a viewer should type for purchasing that event.
    usage: false
  animals:
    # Whether or not the animal list will display the command a viewer should type for purchasing that animal.
    usage: false

commands:
  # Whether or not the command list will display the command's shortcut disclaimer.
  shortcut: true
  # Whether or not the command list will display the command's required user level.
  userlevel: true
  # Whether or not the command list will display the command's uage.
  usage: true

mods:
  # Whether or not the mod list will display the mod's version.
  version: true
  # Whether or not the mod list will display the mod's author(s).
  author: true

store_redirects:
  trait:
    - 'removetrait'
    - 'trait'
    - 'replacetrait'
  kind:
    - 'pawn'
  item:
    - 'backpack'
    - 'surgery'

theme: jekyll-theme-hacker